version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: fishtura_db
    restart: always
    environment:
      POSTGRES_USER: fish
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: fishtura_db
    volumes:
      - /volume1/docker/fishtura/database:/var/lib/postgresql/data
    networks:
      - fishtura_network

  backend_faktura:
    build: ./backend/faktura
    container_name: fishtura_backend_faktura
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://fishtura:secretpassword@fishtura_db:5432/fishtura_db
    networks:
      - fishtura_network
      
  backend_paragon:
    build: ./backend/paragon
    container_name: fishtura_backend_paragon
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://fishtura:secretpassword@fishtura_db:5432/fishtura_db
    networks:
      - fishtura_network 
      
  backend_wz:
    build: ./backend/wz
    container_name: fishtura_backend_wz
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://fishtura:secretpassword@fishtura_db:5432/fishtura_db
    networks:
      - fishtura_network
      
  backend_pz:
    build: ./backend/pz
    container_name: fishtura_backend_pz
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://fishtura:secretpassword@fishtura_db:5432/fishtura_db
    networks:
      - fishtura_network
      
  frontend:
    build: ./frontend
    container_name: fishtura_frontend
    restart: always
    depends_on:
      - backend_faktura
      - backend_paragon
      - backend_wz
      - backend_pz
    ports:
      - "8080:80"
    networks:
      - fishtura_network

networks:
  fishtura_network:
    driver: bridge